/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorProjetosRouteImport } from './routes/professor/projetos'
import { Route as ProfessorProjetosNovoRouteImport } from './routes/professor/projetos.novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorProjetosRoute = ProfessorProjetosRouteImport.update({
  id: '/professor/projetos',
  path: '/professor/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorProjetosNovoRoute = ProfessorProjetosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ProfessorProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/professor/projetos': typeof ProfessorProjetosRouteWithChildren
  '/professor/projetos/novo': typeof ProfessorProjetosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/professor/projetos': typeof ProfessorProjetosRouteWithChildren
  '/professor/projetos/novo': typeof ProfessorProjetosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/professor/projetos': typeof ProfessorProjetosRouteWithChildren
  '/professor/projetos/novo': typeof ProfessorProjetosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/professor/projetos'
    | '/professor/projetos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/professor/projetos'
    | '/professor/projetos/novo'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/login'
    | '/professor/projetos'
    | '/professor/projetos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ProfessorProjetosRoute: typeof ProfessorProjetosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/projetos': {
      id: '/professor/projetos'
      path: '/professor/projetos'
      fullPath: '/professor/projetos'
      preLoaderRoute: typeof ProfessorProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/projetos/novo': {
      id: '/professor/projetos/novo'
      path: '/novo'
      fullPath: '/professor/projetos/novo'
      preLoaderRoute: typeof ProfessorProjetosNovoRouteImport
      parentRoute: typeof ProfessorProjetosRoute
    }
  }
}

interface ProfessorProjetosRouteChildren {
  ProfessorProjetosNovoRoute: typeof ProfessorProjetosNovoRoute
}

const ProfessorProjetosRouteChildren: ProfessorProjetosRouteChildren = {
  ProfessorProjetosNovoRoute: ProfessorProjetosNovoRoute,
}

const ProfessorProjetosRouteWithChildren =
  ProfessorProjetosRoute._addFileChildren(ProfessorProjetosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ProfessorProjetosRoute: ProfessorProjetosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
